Fix gitignore
mobsuccess-devops/github-actions-mobsuccess pull request #16
Opened 2022-01-25 11:33 UTC by pierresisson

### What does it do? Why?

Add `node_modules` in `gitignore`

### QA

### Good To Know

2022-01-25 12:22 UTC, callms requested changes

2022-01-25 12:22 UTC, callms commented on .gitignore
> +/node_modules
C'est über important de bien committer node_modules sinon GitHub ne va pas avoir ses dépendances 

```suggestion
```

2022-01-25 12:22 UTC, callms commented on .gitignore
> +Icon/node_modules
Hum pas sûr du coup

2022-01-26 10:25 UTC, pierresisson commented on .gitignore
> +/node_modules
je close

2022-01-26 10:25 UTC, closed without merging

2022-01-31 08:41 UTC, pierresisson commented on .gitignore
> +Icon/node_modules
yep ;)