Display all monorepo amplify urls
mobsuccess-devops/github-actions-mobsuccess pull request #69
Opened 2023-08-21 09:54 UTC by philippeauriach

### What does it do? Why?
Displays all monorepo amplify urls: they all are deployed, no matter what is touched in the code

2023-08-21 10:10 UTC, callms requested changes
Philosophiquement je me dis que c'est quand même intéressant d'avoir les liens de ce qui est « impacté » par la PR

Pour moi le sujet c'est possiblement que si on change un package, tous les liens n'apparaissent pas, mais je me suis dit que c'était un sujet d'avoir les labels pour les PR de packages ?

2023-08-21 10:11 UTC, pierresisson commented
> Philosophiquement je me dis que c'est quand même intéressant d'avoir les liens de ce qui est « impacté » par la PR
> 
> Pour moi le sujet c'est possiblement que si on change un package, tous les liens n'apparaissent pas, mais je me suis dit que c'était un sujet d'avoir les labels pour les PR de packages ?

pour moi justement c'est l'unique intérêt d'avoir tous les liens quand tu modifies un package

2023-08-21 10:12 UTC, philippeauriach commented
Quelque soit le changement, tout est buildé sur amplify, dès lors qu'il y un fichier dans tout le rpeo qui a été touché, donc même si on touche uniquement au package gitinfo par exemple, tout est quand même deployé (rapidement car mit en cache donc pas rebuildé). 

Par contre on peut mettre en avant ceux qui sont modifiés via les labels si on veut (un emoji par exemple en debut de liste)

2023-08-21 10:16 UTC, philippeauriach commented
La PR est en réponse à ça : https://mobsuccess.slack.com/archives/C05C8CVUA4A/p1692611043405489 
=> Colin a fait un dev sur react-ui
=> le commentaire ne montre aucun url
=> mais amplify a bien tout déployé

2023-08-21 13:59 UTC, callms commented
Oui je suis d'accord, pour moi quand on change un package, alors il faut voir tous les liens

Et le débat c'est est-ce qu'on a besoin d'avoir tous les labels dans GitHub ? je pensais naïvement que oui, mais finalement, peut être que : non :)

2023-08-21 14:01 UTC, philippeauriach commented
Pour moi ce sont deux sujets différents : 
- les labels GH sont la pour informer sur le code touché par la PR (ça peut aider à la review, a la gestion de projet, etc)
- le commentaire avec les liens sert au développeur et au produit pour aller vérifier les devs

2023-08-21 14:02 UTC, callms commented
Je pinaille mais si je fais une modif sur le LCM, ça me gêne d'avoir un lien du LMP parce que tant bien même il aura déployé, il ne devrait pas y avoir de changement, et on prend le risque d'avoir une *fatigue* et que du coup, quand on fait une modif sur react-ui, alors on soit tellement habitué à voir tous les liens qu'on ne pense pas à cliquer dessus

Même remarque sur les emoijs, surtout des emojis impressionnants comme 🔥, j'ai peur qu'à force de les voir, on ne les voit plus

Que dirais-tu de : 
- laisser les labels tels qu'ils sont (à savoir, on a un label si on a un fichier modifié dans le dossier qui correspond)
- on met les liens Amplify de toutes les webapps avec un label
- si une PR a un label de package, on met le liens de toutes les webapps

J'ai l'impression que ça couvre ton besoin, et le mien ?

2023-08-21 14:05 UTC, philippeauriach commented
Je comprends l'idée de la fatigue, et que du coup on ne sache plus quoi tester. J'aime bien ta suggestion, je rajouterai juste une partie "pliable" avec les autres liens, au cas où ? Comme ça ils ne sont pas affichés, mais si besoin, on peut les déplier pour les voir
<details><summary>un peu</summary>comme ça</details>

2023-08-21 14:32 UTC, philippeauriach commented
@callms j'ai update pour avoir : 

- _laisser les labels tels qu'ils sont (à savoir, on a un label si on a un fichier modifié dans le dossier qui correspond)_ => j'ai juste rajouté les labels également pour "configs/" (voir https://github.com/mobsuccess-devops/github-mobsuccess-policy/pull/115)
- _on met les liens Amplify de toutes les webapps avec un label_ => ok
- _si une PR a un label de package, on met le liens de toutes les webapps_ => ok, idem pour un label de configs
- un champ "depliable" avec les autres liens

2023-08-22 09:23 UTC, callms approved these changes
LGTM

2023-08-22 09:24 UTC, callms commented
@philippeauriach au top ! si tu as un exemple de comment ça rend, je suis preneur !

2023-08-22 09:53 UTC, philippeauriach commented
D'après mes calculs, ça rendra comme le commentaire suivant :

2023-08-22 09:59 UTC, philippeauriach commented
AWS Amplify live test URI:
- https://pr-69.lcm.live.mobsuccess.com
- https://pr-69.lco.live.mobsuccess.com

<details>
<summary>More uri</summary>

- https://pr-69.platform-lmp.live.mobsuccess.com
- https://pr-69.dashboard-farly.live.mobsuccess.com
- https://pr-69.dashboard.live.mobsuccess.com
- https://pr-69.toolbox.live.mobsuccess.com

</details>

2023-08-22 10:00 UTC, merged